### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by nfirdavs** [ruby232/redmine_bt#2]
Hi, I use bitnami redmine. I can't install bt4 plugin in redmine. After copy to plugins folder, I do restart all bintnami services. But thin service not start.

![image](https://cloud.githubusercontent.com/assets/17042808/12842270/866d1242-cc13-11e5-94ec-7929335d4f38.png)

Can you help me install this plugin ?

**Comment by ruby232** [comment]
What version of redmine you have?
Show me log file, please.

**Comment by nfirdavs** [comment]
RedminePlusAgile 3.1.1

screen of logs
http://prntscr.com/a0lv4o

**Comment by ruby232** [comment]
I'm sorry,but i cant not replicate this issues and i not see the error.
